[package]
name = "embedded-sensors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accelerometer = "0.12.0"
embedded-hal = "0.2.7"
micromath = { version = "2.0.0", features = ["vector"] }
